# docker-compose.yml
version: "3.7"
services:
  app:
    build:
      args:
        user: lachlan
        uid: 1000
      context: ./
      dockerfile: Dockerfile.app
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - www.lachiegrant.io

  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_HOST
  
  webserver:
    image: nginx:1.17-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./volumes/nginx:/etc/nginx/conf.d
    networks:
      - www.lachiegrant.io

networks:
  www.lachiegrant.io:
    driver: bridge
