# docker-compose.yml
version: "3.7"
services:
  app:
    build:
      args:
        user: lachlan
        uid: 1000
      context: ./
      dockerfile: Dockerfile.app
    container_name: app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - app-network
    links:
      - database
    env_file: .env
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_HOST
      - MYSQL_DRIVER
      - MYSQL_HOST

  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
      - MYSQL_ROOT_HOST
    container_name: database
    networks:
      - app-network

  webserver:
    image: nginx:1.17-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./volumes/nginx:/etc/nginx/conf.d
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
