# docker-compose.yml
version: "3.7"
services:
  webapp:
    build:
      context: .
      dockerfile: ./apache/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
    environment:
      - APP_NAME=lachiegrant.io
  database:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
